[project]
name = "cooking-core"
version = "0.1.0"
description = "This is the core backend API for all of the functions of the cooking assistant."
readme = "README.md"
authors = [
    { name = "nobrien1", email = "nateobrien.dev@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.141.1",
]

[tool.uv]
package = false
